### ISSUE TITLE
Document requirements

### ISSUE THREAD

**Issue by midwan** [muadib25/PomodoroTimer#2]
It would be good to add documentation regarding the requirements to run this from source.
I tried it on a default Ubuntu installation with both `python` and `python3` packages installed, but couldn't get it to run yet:

- using python2, I get:
```
python main.py
  File "main.py", line 101
    canvas.itemconfig(timer_text, text=f"{count_min}:{count_sec}")
                                                                ^
SyntaxError: invalid syntax
```

- using python3, I get:
```
python3 main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from tkinter import *
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by midwan** [comment]
Fixed on my end, this was an issue with my python installation apparently. :)

**Comment by muadib25** [comment]
> Fixed on my end, this was an issue with my python installation apparently. :)

Great that you fixed it. Yes, if run from source it needs the tkinter, I shall add it in the Reqs too
